/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author Admin
 */
public class DoanhThu_Sp extends javax.swing.JPanel {

    /**
     * Creates new form DoanhThu_Sp
     */
    public DoanhThu_Sp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTren = new javax.swing.JPanel();
        jPanelHomNay = new javax.swing.JPanel();
        lblHN = new javax.swing.JLabel();
        txtTongHN = new javax.swing.JTextField();
        jPanel7Ngay = new javax.swing.JPanel();
        lbl7N = new javax.swing.JLabel();
        txtTong7N = new javax.swing.JTextField();
        jPanel1Thang = new javax.swing.JPanel();
        lblT = new javax.swing.JLabel();
        txtTongT = new javax.swing.JTextField();
        jPanelTuy = new javax.swing.JPanel();
        lblTC = new javax.swing.JLabel();
        txtTongTC = new javax.swing.JTextField();
        jPanelChonXTK = new javax.swing.JPanel();
        btnTungay = new javax.swing.JButton();
        btnXuatTK = new javax.swing.JButton();
        lblTu = new javax.swing.JLabel();
        lblDen = new javax.swing.JLabel();
        btnDenngay = new javax.swing.JButton();
        txtTungay = new javax.swing.JTextField();
        txtDenngay = new javax.swing.JTextField();
        jPanelDuoi = new javax.swing.JPanel();
        lblThongKe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelXuatTKDuoi = new javax.swing.JPanel();
        btnLoc = new javax.swing.JButton();
        lblTu1 = new javax.swing.JLabel();
        lblDen1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(250, 238, 232));

        jPanelTren.setBackground(new java.awt.Color(250, 238, 232));
        jPanelTren.setForeground(new java.awt.Color(255, 255, 255));

        jPanelHomNay.setBackground(new java.awt.Color(143, 108, 101));

        lblHN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHN.setForeground(new java.awt.Color(255, 255, 255));
        lblHN.setText("Hôm nay");

        txtTongHN.setBackground(new java.awt.Color(143, 108, 101));
        txtTongHN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTongHN.setForeground(new java.awt.Color(255, 255, 255));
        txtTongHN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTongHN.setText("Tiền");
        txtTongHN.setBorder(null);

        javax.swing.GroupLayout jPanelHomNayLayout = new javax.swing.GroupLayout(jPanelHomNay);
        jPanelHomNay.setLayout(jPanelHomNayLayout);
        jPanelHomNayLayout.setHorizontalGroup(
            jPanelHomNayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomNayLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblHN)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanelHomNayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTongHN)
                .addContainerGap())
        );
        jPanelHomNayLayout.setVerticalGroup(
            jPanelHomNayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomNayLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongHN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7Ngay.setBackground(new java.awt.Color(143, 108, 101));

        lbl7N.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl7N.setForeground(new java.awt.Color(255, 255, 255));
        lbl7N.setText("7 ngày");

        txtTong7N.setBackground(new java.awt.Color(143, 108, 101));
        txtTong7N.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTong7N.setForeground(new java.awt.Color(255, 255, 255));
        txtTong7N.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTong7N.setText("Tiền");
        txtTong7N.setBorder(null);

        javax.swing.GroupLayout jPanel7NgayLayout = new javax.swing.GroupLayout(jPanel7Ngay);
        jPanel7Ngay.setLayout(jPanel7NgayLayout);
        jPanel7NgayLayout.setHorizontalGroup(
            jPanel7NgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7NgayLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lbl7N)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7NgayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTong7N)
                .addContainerGap())
        );
        jPanel7NgayLayout.setVerticalGroup(
            jPanel7NgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7NgayLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl7N)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTong7N, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Thang.setBackground(new java.awt.Color(143, 108, 101));

        lblT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblT.setForeground(new java.awt.Color(255, 255, 255));
        lblT.setText("Tháng");

        txtTongT.setBackground(new java.awt.Color(143, 108, 101));
        txtTongT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTongT.setForeground(new java.awt.Color(255, 255, 255));
        txtTongT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTongT.setText("Tiền");
        txtTongT.setBorder(null);

        javax.swing.GroupLayout jPanel1ThangLayout = new javax.swing.GroupLayout(jPanel1Thang);
        jPanel1Thang.setLayout(jPanel1ThangLayout);
        jPanel1ThangLayout.setHorizontalGroup(
            jPanel1ThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ThangLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblT)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1ThangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTongT)
                .addContainerGap())
        );
        jPanel1ThangLayout.setVerticalGroup(
            jPanel1ThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ThangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTuy.setBackground(new java.awt.Color(143, 108, 101));
        jPanelTuy.setForeground(new java.awt.Color(255, 255, 255));

        lblTC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTC.setForeground(new java.awt.Color(255, 255, 255));
        lblTC.setText("Tùy chỉnh");

        txtTongTC.setBackground(new java.awt.Color(143, 108, 101));
        txtTongTC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTongTC.setForeground(new java.awt.Color(255, 255, 255));
        txtTongTC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTongTC.setText("Tiền");
        txtTongTC.setBorder(null);

        javax.swing.GroupLayout jPanelTuyLayout = new javax.swing.GroupLayout(jPanelTuy);
        jPanelTuy.setLayout(jPanelTuyLayout);
        jPanelTuyLayout.setHorizontalGroup(
            jPanelTuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTuyLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblTC)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanelTuyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTongTC)
                .addContainerGap())
        );
        jPanelTuyLayout.setVerticalGroup(
            jPanelTuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTuyLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongTC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanelChonXTK.setBackground(new java.awt.Color(250, 238, 232));

        btnTungay.setText("=");

        btnXuatTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatTK.setText("Xuất TK");

        lblTu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTu.setText("Từ");

        lblDen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDen.setText("Đến:");

        btnDenngay.setText("+");

        javax.swing.GroupLayout jPanelChonXTKLayout = new javax.swing.GroupLayout(jPanelChonXTK);
        jPanelChonXTK.setLayout(jPanelChonXTKLayout);
        jPanelChonXTKLayout.setHorizontalGroup(
            jPanelChonXTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChonXTKLayout.createSequentialGroup()
                .addGap(40, 60, Short.MAX_VALUE)
                .addGroup(jPanelChonXTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTu)
                    .addComponent(lblDen))
                .addGap(18, 18, 18)
                .addGroup(jPanelChonXTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChonXTKLayout.createSequentialGroup()
                        .addComponent(txtDenngay, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDenngay))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChonXTKLayout.createSequentialGroup()
                        .addComponent(txtTungay, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTungay)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXuatTK))
        );
        jPanelChonXTKLayout.setVerticalGroup(
            jPanelChonXTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChonXTKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelChonXTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDenngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDenngay)
                    .addComponent(lblTu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelChonXTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTungay)
                    .addComponent(txtTungay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChonXTKLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXuatTK, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelTrenLayout = new javax.swing.GroupLayout(jPanelTren);
        jPanelTren.setLayout(jPanelTrenLayout);
        jPanelTrenLayout.setHorizontalGroup(
            jPanelTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrenLayout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(jPanelTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelChonXTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTrenLayout.createSequentialGroup()
                        .addComponent(jPanelHomNay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jPanel7Ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jPanel1Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jPanelTuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        jPanelTrenLayout.setVerticalGroup(
            jPanelTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrenLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelHomNay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7Ngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1Thang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanelChonXTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelDuoi.setBackground(new java.awt.Color(250, 238, 232));

        lblThongKe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblThongKe.setText("Thống kê sản phẩm:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanelXuatTKDuoi.setBackground(new java.awt.Color(250, 238, 232));

        btnLoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoc.setText("Loc");

        lblTu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTu1.setText("Từ ngày:");

        lblDen1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDen1.setText("Đến ngày:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Loại sản phẩm:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Trạng thái:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));

        javax.swing.GroupLayout jPanelXuatTKDuoiLayout = new javax.swing.GroupLayout(jPanelXuatTKDuoi);
        jPanelXuatTKDuoi.setLayout(jPanelXuatTKDuoiLayout);
        jPanelXuatTKDuoiLayout.setHorizontalGroup(
            jPanelXuatTKDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelXuatTKDuoiLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelXuatTKDuoiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelXuatTKDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTu1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(jPanelXuatTKDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblDen1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanelXuatTKDuoiLayout.setVerticalGroup(
            jPanelXuatTKDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelXuatTKDuoiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelXuatTKDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTu1)
                    .addComponent(lblDen1))
                .addGroup(jPanelXuatTKDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelXuatTKDuoiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(136, 136, 136))
                    .addGroup(jPanelXuatTKDuoiLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelXuatTKDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanelDuoiLayout = new javax.swing.GroupLayout(jPanelDuoi);
        jPanelDuoi.setLayout(jPanelDuoiLayout);
        jPanelDuoiLayout.setHorizontalGroup(
            jPanelDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDuoiLayout.createSequentialGroup()
                .addGroup(jPanelDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDuoiLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblThongKe)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDuoiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanelXuatTKDuoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDuoiLayout.setVerticalGroup(
            jPanelDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDuoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThongKe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelXuatTKDuoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDuoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDuoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDenngay;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnTungay;
    private javax.swing.JButton btnXuatTK;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1Thang;
    private javax.swing.JPanel jPanel7Ngay;
    private javax.swing.JPanel jPanelChonXTK;
    private javax.swing.JPanel jPanelDuoi;
    private javax.swing.JPanel jPanelHomNay;
    private javax.swing.JPanel jPanelTren;
    private javax.swing.JPanel jPanelTuy;
    private javax.swing.JPanel jPanelXuatTKDuoi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl7N;
    private javax.swing.JLabel lblDen;
    private javax.swing.JLabel lblDen1;
    private javax.swing.JLabel lblHN;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblTC;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblTu;
    private javax.swing.JLabel lblTu1;
    private javax.swing.JTextField txtDenngay;
    private javax.swing.JTextField txtTong7N;
    private javax.swing.JTextField txtTongHN;
    private javax.swing.JTextField txtTongT;
    private javax.swing.JTextField txtTongTC;
    private javax.swing.JTextField txtTungay;
    // End of variables declaration//GEN-END:variables
}
