/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


public class ThongKe extends javax.swing.JPanel {

    DoanhThu_Sp dtsp= new DoanhThu_Sp();
    GiaoCa giaoca = new GiaoCa();
    public ThongKe() {
        initComponents();
        jLayeredPane1.add(dtsp);
        jLayeredPane1.add(giaoca);
        dtsp.setVisible(false);
        giaoca.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jOptionPane1 = new javax.swing.JOptionPane();
        jPanelLon = new javax.swing.JPanel();
        jPanelNav = new javax.swing.JPanel();
        btnDTSP = new javax.swing.JButton();
        btnGiaoCa = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        setBackground(new java.awt.Color(250, 238, 232));

        jPanelLon.setBackground(new java.awt.Color(250, 238, 232));

        javax.swing.GroupLayout jPanelLonLayout = new javax.swing.GroupLayout(jPanelLon);
        jPanelLon.setLayout(jPanelLonLayout);
        jPanelLonLayout.setHorizontalGroup(
            jPanelLonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanelLonLayout.setVerticalGroup(
            jPanelLonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelNav.setBackground(new java.awt.Color(250, 238, 232));

        btnDTSP.setBackground(new java.awt.Color(143, 108, 101));
        btnDTSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDTSP.setForeground(new java.awt.Color(255, 255, 255));
        btnDTSP.setText("Doanh thu-Sản Phẩm");
        btnDTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDTSPActionPerformed(evt);
            }
        });

        btnGiaoCa.setBackground(new java.awt.Color(143, 108, 101));
        btnGiaoCa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGiaoCa.setForeground(new java.awt.Color(255, 255, 255));
        btnGiaoCa.setText("Giao ca");
        btnGiaoCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaoCaActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelNavLayout = new javax.swing.GroupLayout(jPanelNav);
        jPanelNav.setLayout(jPanelNavLayout);
        jPanelNavLayout.setHorizontalGroup(
            jPanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDTSP)
                .addGap(18, 18, 18)
                .addComponent(btnGiaoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelNavLayout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelNavLayout.setVerticalGroup(
            jPanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGiaoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanelLon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDTSPActionPerformed
        dtsp.setVisible(true);
        giaoca.setVisible(false);
    }//GEN-LAST:event_btnDTSPActionPerformed

    private void btnGiaoCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaoCaActionPerformed
        dtsp.setVisible(false);
        giaoca.setVisible(true);
    }//GEN-LAST:event_btnGiaoCaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDTSP;
    private javax.swing.JButton btnGiaoCa;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanelLon;
    private javax.swing.JPanel jPanelNav;
    // End of variables declaration//GEN-END:variables
}
